### ISSUE TITLE
doi compound query fails due to parsing error

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/montysolr#70] opened 2017-06-20 12:41 UTC
This query works:
```
doi:"10.1016/j.cnsns.2014.03.026" OR doi:"10.1016/j.asr.2014.07.018" OR doi:"10.1088/0004-6256/147/3/57"
```
But this one throws a parsing error:
```
doi:("10.1016/j.cnsns.2014.03.026" OR "10.1016/j.asr.2014.07.018" OR "10.1088/0004-6256/147/3/57")
```

**Comment by JCRPaquin** [comment] 2023-10-13 15:45
Duplicate of #25

**Closed by JCRPaquin** 2023-10-13 15:45 UTC
Labels: query, doi, parsing
